name:                deploybot-hs
version:             0.1.0.0
github:              "Azwraith42/deploybot-hs"
license:             BSD3
author:              "Alec Reeves"
maintainer:          "alchreeves@gmail.com"
copyright:           "2018 Alec Reeves"

extra-source-files:
- README.md

synopsis: a haskell integration for a slackbot
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Azwraith42/deploybot-hs#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  deploybot-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - deploybot-hs

tests:
  deploybot-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -fprint-potential-instances
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - deploybot-hs
    - QuickCheck
    - quickcheck-assertions
    - quickcheck-instances
    - tasty
    - tasty-hunit
    - tasty-quickcheck
